version: "3.0"

services:
  chaturbate-dvr-web:
    container_name: chaturbate-dvr-web
    build:
      context: .
      dockerfile: web.Dockerfile
    environment:
      - GUI_USERNAME=johndoe
      - GUI_PASSWORD=password
    ports:
      - "8080:8080"